import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Cabin } from 'next/font/google'

const cabin = Cabin({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pl">
      <body className={cabin.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
